# Servers from which we can download Breakpad .sym files
[symbols.breakpad]
servers = [
  "https://symbols.mozilla.org/try"
]
cache_dir = "./cache/symbols/breakpad/"
symindex_dir = "./cache/symbols/breakpad-symindex/"

# Servers from which we can download Windows .pdb, .exe and .dll files
[symbols.windows]
servers = [
  "https://symbols.mozilla.org/try",
  "https://msdl.microsoft.com/download/symbols"
]
cache_dir = "./cache/symbols/windows/"

# Settings for automatic file deletion
[quota]
managed_dir = "./cache/symbols"
db_path = "./cache/symbols.db"
