name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  SCCACHE_VERSION: "v0.10.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
        with:
          version: ${{ env.SCCACHE_VERSION }}

      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
      - name: Check formatting
        run: cargo fmt -- --check --verbose
      - name: Clippy
        run: cargo clippy --verbose -- -Dwarnings
